import type {
  ActionPlan,
  ActionRecommendation,
  Customer,
  IntelligenceSignal,
  Transaction,
} from "@/types/domain";

/**
 * Intentionally synthetic Phase 3 data. It powers the UI without claiming to be
 * PayPal Sandbox history or a real merchant ledger.
 */
const demoCustomerSeed = [
  {
    id: "cust_alex",
    name: "Alex Morgan",
    initials: "AM",
    segment: "at_risk",
    relationshipValue: 1084,
    lastPaymentAt: "2026-09-08T09:30:00.000Z",
    risk: "high",
    source: "demo",
    paymentDna: {
      typicalPayment: 120,
      frequencyDays: 14,
      averageDelayDays: 1.2,
      recentChangePercent: -40,
      consistency: "high",
      riskSignals: 2,
      confidence: 0.87,
      state: "declining",
    },
  },
  {
    id: "cust_priya",
    name: "Priya Shah",
    initials: "PS",
    segment: "repeat",
    relationshipValue: 2240,
    lastPaymentAt: "2026-09-27T16:15:00.000Z",
    risk: "medium",
    source: "demo",
    paymentDna: {
      typicalPayment: 310,
      frequencyDays: 21,
      averageDelayDays: 0.4,
      recentChangePercent: -18,
      consistency: "high",
      riskSignals: 1,
      confidence: 0.81,
      state: "watch",
    },
  },
  {
    id: "cust_mateo",
    name: "Mateo Silva",
    initials: "MS",
    segment: "repeat",
    relationshipValue: 1680,
    lastPaymentAt: "2026-09-30T11:40:00.000Z",
    risk: "low",
    source: "demo",
    paymentDna: {
      typicalPayment: 190,
      frequencyDays: 14,
      averageDelayDays: 0.7,
      recentChangePercent: 8,
      consistency: "high",
      riskSignals: 0,
      confidence: 0.92,
      state: "stable",
    },
  },
  {
    id: "cust_nora",
    name: "Nora Chen",
    initials: "NC",
    segment: "at_risk",
    relationshipValue: 720,
    lastPaymentAt: "2026-09-03T10:10:00.000Z",
    risk: "high",
    source: "demo",
    paymentDna: {
      typicalPayment: 88,
      frequencyDays: 10,
      averageDelayDays: 2.6,
      recentChangePercent: -32,
      consistency: "medium",
      riskSignals: 2,
      confidence: 0.73,
      state: "delayed",
    },
  },
  {
    id: "cust_jordan",
    name: "Jordan Lee",
    initials: "JL",
    segment: "new",
    relationshipValue: 245,
    lastPaymentAt: "2026-09-29T14:20:00.000Z",
    risk: "medium",
    source: "demo",
    paymentDna: {
      typicalPayment: 245,
      frequencyDays: 30,
      averageDelayDays: 0,
      recentChangePercent: 0,
      consistency: "medium",
      riskSignals: 1,
      confidence: 0.54,
      state: "unusual",
    },
  },
  {
    id: "cust_samara",
    name: "Samara Rao",
    initials: "SR",
    segment: "repeat",
    relationshipValue: 1320,
    lastPaymentAt: "2026-09-26T08:05:00.000Z",
    risk: "medium",
    source: "demo",
    paymentDna: {
      typicalPayment: 165,
      frequencyDays: 15,
      averageDelayDays: 1.1,
      recentChangePercent: -21,
      consistency: "high",
      riskSignals: 1,
      confidence: 0.78,
      state: "watch",
    },
  },
  {
    id: "cust_owen",
    name: "Owen Brooks",
    initials: "OB",
    segment: "repeat",
    relationshipValue: 985,
    lastPaymentAt: "2026-09-28T18:55:00.000Z",
    risk: "low",
    source: "demo",
    paymentDna: {
      typicalPayment: 140,
      frequencyDays: 14,
      averageDelayDays: 0.8,
      recentChangePercent: -6,
      consistency: "high",
      riskSignals: 0,
      confidence: 0.89,
      state: "stable",
    },
  },
] as const;

export const demoCustomers: readonly Customer[] = demoCustomerSeed.map((customer, index) => ({
  ...customer,
  paypalCustomerId: null,
  payerReference: null,
  displayName: customer.name,
  email: null,
  country: null,
  totalPayments: index === 0 ? 9 : index === 1 ? 7 : index === 2 ? 8 : index === 3 ? 5 : 3,
  totalValue: customer.relationshipValue,
  primaryCurrency: "USD",
  valueByCurrency: { USD: customer.relationshipValue },
  firstSeenAt: "2026-05-01T09:00:00.000Z",
}));

const demoTransactionSeed = [
  {
    id: "txn_demo_1042",
    customerId: "cust_mateo",
    amount: 190,
    currency: "USD",
    status: "completed",
    occurredAt: "2026-09-30T11:40:00.000Z",
    relationship: "repeat",
    source: "demo",
    aiInterpretation: "Payment arrived within Mateo’s stable 14-day rhythm.",
  },
  {
    id: "txn_demo_1041",
    customerId: "cust_jordan",
    amount: 540,
    currency: "USD",
    status: "pending",
    occurredAt: "2026-09-29T14:20:00.000Z",
    relationship: "new",
    source: "demo",
    aiInterpretation: "Amount is above Jordan’s short history baseline; review is recommended.",
  },
  {
    id: "txn_demo_1040",
    customerId: "cust_owen",
    amount: 140,
    currency: "USD",
    status: "completed",
    occurredAt: "2026-09-28T18:55:00.000Z",
    relationship: "repeat",
    source: "demo",
    aiInterpretation: "Normal recurring payment behavior.",
  },
  {
    id: "txn_demo_1039",
    customerId: "cust_priya",
    amount: 310,
    currency: "USD",
    status: "completed",
    occurredAt: "2026-09-27T16:15:00.000Z",
    relationship: "repeat",
    source: "demo",
    aiInterpretation: "Consistent payment, but frequency is softening against the prior period.",
  },
  {
    id: "txn_demo_1038",
    customerId: "cust_samara",
    amount: 165,
    currency: "USD",
    status: "failed",
    occurredAt: "2026-09-26T08:05:00.000Z",
    relationship: "at_risk",
    source: "demo",
    aiInterpretation: "A recent failed payment makes respectful merchant follow-up timely.",
  },
] as const;

export const demoTransactions: readonly Transaction[] = demoTransactionSeed.map((transaction) => ({
  ...transaction,
  paypalTransactionId: null,
  paypalOrderId: null,
  paymentMethod: null,
  payerReference: null,
  rawReference: null,
  createdAt: transaction.occurredAt,
  updatedAt: transaction.occurredAt,
}));

export const demoSignals: readonly IntelligenceSignal[] = [
  {
    id: "signal_revenue_velocity",
    title: "Revenue velocity changed",
    type: "revenue_velocity",
    severity: "high",
    confidence: 0.87,
    why: "Current-week demo revenue is 18% below the comparable prior period.",
    what: "Seven repeat-customer payment patterns moved outside their normal cadence or value range.",
    impact: "Near-term cash-flow visibility requires attention; this is not a revenue guarantee.",
    requiredAction: "Review the consent-based action plan.",
    affectedCustomerIds: [
      "cust_alex",
      "cust_priya",
      "cust_nora",
      "cust_samara",
      "cust_jordan",
      "cust_owen",
      "cust_mateo",
    ],
    source: "demo",
  },
  {
    id: "signal_alex_cadence",
    title: "Expected payment rhythm interrupted",
    type: "payment_behavior_change",
    severity: "high",
    confidence: 0.87,
    why: "Alex is 11 days beyond a historically consistent 14-day payment rhythm.",
    what: "Alex’s recent payment activity is 40% lower than the baseline.",
    impact: "A prepared reminder could help the merchant follow up at the right time.",
    requiredAction: "Prepare a merchant-reviewed reminder draft.",
    affectedCustomerIds: ["cust_alex"],
    source: "demo",
  },
  {
    id: "signal_jordan_unusual",
    title: "Unusual value pattern",
    type: "unusual_activity",
    severity: "medium",
    confidence: 0.68,
    why: "Jordan’s pending demo transaction is materially larger than their limited history.",
    what: "The signal is an anomaly review request, not a fraud conclusion.",
    impact: "A quick human review may reduce operational uncertainty.",
    requiredAction: "Open an unusual-activity review.",
    affectedCustomerIds: ["cust_jordan"],
    source: "demo",
  },
] as const;

export const demoActions: readonly ActionRecommendation[] = [
  {
    id: "action_reminders",
    version: 1,
    kind: "prepare_payment_reminder",
    title: "Prepare 6 payment reminder drafts",
    status: "awaiting_approval",
    customerIds: [
      "cust_alex",
      "cust_nora",
      "cust_samara",
      "cust_priya",
      "cust_owen",
      "cust_mateo",
    ],
    why: "These demo customer profiles show disrupted cadence, a decline in activity, or a recent payment failure.",
    whatWillHappen: "PayPulse will prepare internal merchant-review reminder drafts only. Nothing is sent to a customer.",
    expectedImpact: "Helps prioritize timely follow-up; no recovery outcome is promised.",
    risk: "Low operational risk. No payment API call or customer message occurs in Phase 3.",
    confidence: 0.84,
    requiresApproval: true,
    source: "demo",
  },
  {
    id: "action_retention",
    version: 1,
    kind: "recommend_retention_follow_up",
    title: "Prepare 2 retention follow-up playbooks",
    status: "recommended",
    customerIds: ["cust_alex", "cust_priya"],
    why: "Relationship value is high while payment momentum has softened.",
    whatWillHappen: "PayPulse will prepare merchant-facing retention context; no offer is sent or applied.",
    expectedImpact: "Supports a more relevant retention conversation.",
    risk: "No financial action. Merchant review remains mandatory.",
    confidence: 0.77,
    requiresApproval: true,
    source: "demo",
  },
  {
    id: "action_unusual_review",
    version: 1,
    kind: "open_unusual_activity_review",
    title: "Open 1 unusual activity review",
    status: "recommended",
    customerIds: ["cust_jordan"],
    why: "One pending demo payment is materially larger than a limited historical baseline.",
    whatWillHappen: "PayPulse will prepare an internal review case. It does not block, capture, or refund anything.",
    expectedImpact: "Creates an explainable queue for merchant investigation.",
    risk: "Signal is not a fraud verdict and should be reviewed by a human.",
    confidence: 0.68,
    requiresApproval: true,
    source: "demo",
  },
] as const;

export const demoActionPlan: ActionPlan = {
  id: "plan_demo_weekly_pulse",
  title: "Revenue velocity action plan",
  status: "awaiting_approval",
  actionIds: demoActions.map((action) => action.id),
  summary:
    "6 reminder drafts • 2 retention follow-ups • 1 unusual activity review",
  source: "demo",
};
