"use client";

import { motion, useReducedMotion } from "framer-motion";
import { Activity, BrainCircuit, CircleAlert, Database, GitBranch, Sparkles } from "lucide-react";
import { useState, type ReactNode } from "react";

import { IntelligenceCore } from "@/components/3d/intelligence-core";
import { DataSourceSwitch } from "@/components/ui/data-source-switch";
import { IntelligenceLifecycle, intelligenceStages, type IntelligenceStage } from "@/components/ui/intelligence-lifecycle";
import { formatCurrency } from "@/lib/format";
import type { CoreState, DeterministicIntelligence, Insight } from "@/types/domain";

export function IntelligenceLab({ intelligence }: { readonly intelligence: DeterministicIntelligence }) {
  const reduceMotion = useReducedMotion();
  const [selectedStage, setSelectedStage] = useState<IntelligenceStage>(intelligenceStages[1]!);
  const actionable = intelligence.insights.filter((insight) => insight.type !== "insufficient_data");
  const coreState: CoreState = actionable.length ? "insight_detected" : "analyzing";

  return <div className="space-y-5">
    <section className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-violet-200">PayPulse reasoning engine</p><h1 className="mt-2 max-w-3xl font-[family-name:var(--font-display)] text-3xl font-semibold tracking-[-.055em] text-white sm:text-5xl">Inside the payment <span className="text-violet-200">intelligence loop.</span></h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Payment DNA, deterministic signals, evidence, and optional AI explanations occupy distinct layers. No AI explanation can decide eligibility or execute a financial action.</p></div><DataSourceSwitch source={intelligence.source} sandboxConnected={intelligence.source === "paypal_sandbox"} /></section>

    <section className="relative isolate min-h-[630px] overflow-hidden rounded-[2rem] border border-violet-300/15 bg-[radial-gradient(circle_at_50%_48%,rgba(117,67,201,.17),transparent_42%),rgba(5,10,25,.72)] p-4 sm:p-6"><div className="grid-noise pointer-events-none absolute inset-0 opacity-65" /><div className="relative z-10 flex items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.19em] text-violet-200"><BrainCircuit size={14} /> Neural payment graph</p><p className="mt-1 text-xs text-slate-500">Evidence flows into a deterministic eligibility boundary before any recommendation is exposed.</p></div><span className="rounded-full border border-violet-300/20 bg-violet-300/[.08] px-2.5 py-1 text-[9px] font-semibold uppercase tracking-[.13em] text-violet-100">{actionable.length} active signal{actionable.length === 1 ? "" : "s"}</span></div><div className="absolute inset-x-2 top-14 bottom-24 sm:inset-x-10"><IntelligenceCore state={coreState} customers={[]} onStageSelect={setSelectedStage} /></div><div className="holo-panel absolute bottom-6 left-6 z-10 hidden w-[260px] rounded-2xl p-4 lg:block"><p className="text-[9px] font-semibold uppercase tracking-[.15em] text-violet-200">Selected reasoning node</p><p className="mt-2 text-xl font-semibold text-white">{selectedStage.label}</p><p className="mt-2 text-xs leading-5 text-slate-400">{stageDetail(selectedStage)}</p></div><div className="holo-panel absolute right-6 top-28 z-10 hidden w-[220px] rounded-2xl p-4 lg:block"><p className="flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[.15em] text-cyan-200"><GitBranch size={13} /> Source boundary</p><p className="mt-3 text-sm font-medium text-white">{intelligence.source === "demo" ? "Explicit Demo Data" : "PayPal Sandbox"}</p><p className="mt-2 text-xs leading-5 text-slate-500">No cross-source learning or silent demo substitution.</p></div><div className="absolute inset-x-4 bottom-4 z-10 rounded-2xl border border-white/[.09] bg-[#071126]/75 p-3 backdrop-blur-xl sm:inset-x-6"><IntelligenceLifecycle state={coreState} selectedStage={selectedStage.id} onSelect={setSelectedStage} /></div></section>

    <section className="grid gap-4 md:grid-cols-3"><Metric icon={<Activity size={15} />} label="Observed activity" value={String(intelligence.customerActivityCount)} detail="payer relationships with activity" /><Metric icon={<Database size={15} />} label="Payment DNA profiles" value={String(intelligence.customerProfiles.length)} detail="computed from normalized facts" tone="violet" /><Metric icon={<Sparkles size={15} />} label="Deterministic signals" value={String(actionable.length)} detail="evidence-backed; not autonomous" tone="cyan" /></section>

    <section className="grid gap-4 xl:grid-cols-[.78fr_1.22fr]"><article className="holo-panel rounded-2xl p-5"><p className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.17em] text-cyan-200"><Activity size={14} /> Signal propagation</p><div className="mt-5 space-y-1">{intelligenceStages.map((stage, index) => <button key={stage.id} type="button" onClick={() => setSelectedStage(stage)} className={`focus-ring flex w-full items-center gap-3 rounded-xl p-3 text-left transition ${selectedStage.id === stage.id ? "bg-cyan-300/[.09] text-cyan-50" : "text-slate-400 hover:bg-white/[.035]"}`}><span className="grid size-7 place-items-center rounded-full border border-white/[.1] text-[10px] font-semibold">0{index + 1}</span><span><span className="block text-sm font-medium">{stage.label}</span><span className="mt-0.5 block text-xs text-slate-500">{stage.detail}</span></span></button>)}</div></article><article className="holo-panel rounded-2xl p-5"><p className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.17em] text-violet-200"><CircleAlert size={14} /> Evidence-backed signal field</p><div className="mt-4 space-y-3">{intelligence.insights.length ? intelligence.insights.map((insight, index) => <motion.div key={insight.id} initial={reduceMotion ? false : { opacity: 0, x: 10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .06 }}><InsightObject insight={insight} source={intelligence.source} /></motion.div>) : <p className="rounded-xl border border-white/[.07] bg-black/10 p-5 text-sm text-slate-500">No behavior change is asserted beyond the available evidence.</p>}</div></article></section>

    <section className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]"><article className="holo-panel rounded-2xl p-5"><p className="text-[10px] font-semibold uppercase tracking-[.17em] text-cyan-200">Payment DNA & revenue facts</p><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{intelligence.revenueByCurrency.length ? intelligence.revenueByCurrency.map((metric) => <div key={metric.currency} className="rounded-xl border border-white/[.07] bg-black/10 p-4"><p className="text-[9px] font-semibold uppercase tracking-[.13em] text-slate-500">{metric.currency} observed volume</p><p className="mt-2 text-xl font-semibold text-white">{formatCurrency(metric.totalPaymentValue, metric.currency)}</p><p className="mt-2 text-xs leading-5 text-slate-400">{metric.transactionCount} completed payment{metric.transactionCount === 1 ? "" : "s"} · recent vs historical {metric.valueChangePercent === null ? "not comparable" : `${metric.valueChangePercent.toFixed(1)}%`}</p></div>) : <p className="text-sm text-slate-500">No completed payment values are available.</p>}</div></article><article className="holo-panel rounded-2xl p-5"><p className="text-[10px] font-semibold uppercase tracking-[.17em] text-violet-200">Methodology boundary</p><p className="mt-3 text-sm leading-6 text-slate-400">{intelligence.methodology}</p><p className="mt-4 border-t border-white/[.08] pt-4 text-xs leading-5 text-slate-500">Deterministic evidence decides whether an action can be proposed. AI-generated language, when requested elsewhere, remains a distinct explanatory layer.</p></article></section>
  </div>;
}

function Metric({ icon, label, value, detail, tone = "cyan" }: { readonly icon: ReactNode; readonly label: string; readonly value: string; readonly detail: string; readonly tone?: "cyan" | "violet" }) { const color = tone === "violet" ? "text-violet-100 border-violet-300/15" : "text-cyan-100 border-cyan-300/15"; return <article className={`holo-panel rounded-2xl border p-4 ${color}`}><p className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.15em]">{icon}{label}</p><p className="mt-3 text-2xl font-semibold text-white">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></article>; }
function InsightObject({ insight, source }: { readonly insight: Insight; readonly source: DeterministicIntelligence["source"] }) { return <article className="rounded-2xl border border-white/[.08] bg-black/10 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-cyan-200">Deterministic signal</p><h2 className="mt-1 text-lg font-semibold text-white">{insight.title}</h2></div><span className="rounded-full border border-cyan-300/15 bg-cyan-300/[.06] px-2.5 py-1 text-[10px] font-semibold text-cyan-100">{Math.round(insight.confidence * 100)}%</span></div><p className="mt-3 text-sm leading-6 text-slate-400">{insight.summary}</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{insight.evidence.map((evidence) => <div key={`${insight.id}-${evidence.label}`} className="rounded-lg border border-white/[.06] p-2.5"><p className="text-[9px] uppercase tracking-[.12em] text-slate-500">{evidence.label}</p><p className="mt-1 text-xs leading-5 text-slate-300">{evidence.value}</p></div>)}</div><p className="mt-4 border-t border-white/[.07] pt-3 text-xs text-slate-500">{source === "demo" ? "Explicit demo evidence" : "PayPal Sandbox-derived evidence"} · {insight.methodology}</p></article>; }
function stageDetail(stage: IntelligenceStage): string { return stage.id === "observe" ? "Normalized payment facts enter with their source boundary intact." : stage.id === "understand" ? "Payment DNA converts observed history into explainable behavior features." : stage.id === "predict" ? "Patterns are confidence-scoped and never become automatic financial facts." : stage.id === "recommend" ? "Only deterministic eligibility permits a reviewable recommendation." : stage.id === "approve" ? "A merchant decision remains mandatory before an execution route can proceed." : stage.id === "act" ? "Only an explicit Sandbox flow can create a server-configured verification order." : "Server-verified outcomes can return a learning signal to Payment DNA."; }
