"use client";

import Link from "next/link";
import { ArrowLeft, BrainCircuit, CircleAlert, Database, Orbit, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";

import { IntelligenceCore } from "@/components/3d/intelligence-core";
import { DataSourceSwitch } from "@/components/ui/data-source-switch";
import { IntelligenceLifecycle } from "@/components/ui/intelligence-lifecycle";
import { formatCurrency, formatRelativeDate, formatTimestamp } from "@/lib/format";
import type { ActionOutcome, AiInsightExplanation, Customer, DataSource, Insight, LearningEvent, PaymentDnaProfile, Transaction } from "@/types/domain";

type ExplanationState = { readonly loading: boolean; readonly explanation: AiInsightExplanation | null; readonly message: string | null };
type LearningState = { readonly outcomes: readonly ActionOutcome[]; readonly events: readonly LearningEvent[]; readonly latestOutcome: ActionOutcome | null; readonly latestLearning: LearningEvent | null };

export function CustomerIntelligence({ customer, transactions, profile, insights, source }: { readonly customer: Customer; readonly transactions: readonly Transaction[]; readonly profile: PaymentDnaProfile; readonly insights: readonly Insight[]; readonly source: DataSource }) {
  const customerTransactions = transactions.filter((transaction) => transaction.customerId === customer.id);
  const [ai, setAi] = useState<ExplanationState>({ loading: false, explanation: null, message: null });
  const [learning, setLearning] = useState<LearningState | null>(null);
  const sourceSuffix = source === "demo" ? "?source=demo" : "";
  const coreState = profile.state === "insufficient_data" ? "idle" : insights.length ? "insight_detected" : "analyzing" as const;

  useEffect(() => {
    let active = true;
    void fetch(`/api/customers/${customer.id}/learning${sourceSuffix}`)
      .then(async (response) => response.ok ? response.json() as Promise<{ data?: LearningState }> : null)
      .then((payload) => { if (active && payload?.data) setLearning(payload.data); })
      .catch(() => undefined);
    return () => { active = false; };
  }, [customer.id, sourceSuffix]);

  async function requestExplanation(): Promise<void> {
    setAi({ loading: true, explanation: null, message: null });
    try {
      const response = await fetch(`/api/intelligence/analyze${sourceSuffix}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ customerId: customer.id }) });
      const payload = await response.json() as { data?: { ai?: { explanation?: AiInsightExplanation | null; message?: string | null } }; error?: string };
      const result = payload.data?.ai;
      setAi({ loading: false, explanation: result?.explanation ?? null, message: result?.message ?? payload.error ?? "AI explanation temporarily unavailable." });
    } catch { setAi({ loading: false, explanation: null, message: "AI explanation temporarily unavailable." }); }
  }

  return <div className="space-y-5">
    <Link href={`/customers${sourceSuffix}`} className="focus-ring inline-flex items-center gap-2 rounded-lg text-sm text-slate-400 transition hover:text-cyan-100"><ArrowLeft size={15} /> Return to customer constellation</Link>
    <section className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div className="flex items-center gap-4"><span className="grid size-14 place-items-center rounded-2xl border border-cyan-300/20 bg-cyan-300/[.09] text-lg font-semibold text-cyan-100">{customer.initials}</span><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-cyan-200">Customer intelligence orbit</p><h1 className="mt-1 font-[family-name:var(--font-display)] text-3xl font-semibold tracking-[-.055em] text-white sm:text-5xl">{customer.displayName}</h1><p className="mt-2 text-sm text-slate-400">{profile.transactionCount} observed completed payment{profile.transactionCount === 1 ? "" : "s"} · {source === "paypal_sandbox" ? "PayPal Sandbox" : "Explicit Demo Data"}</p></div></div><DataSourceSwitch source={source} sandboxConnected={source === "paypal_sandbox"} /></section>

    <section className="relative isolate min-h-[640px] overflow-hidden rounded-[2rem] border border-cyan-300/15 bg-[radial-gradient(circle_at_50%_45%,rgba(23,141,215,.15),transparent_41%),rgba(5,10,25,.72)] p-4 sm:p-6"><div className="grid-noise pointer-events-none absolute inset-0 opacity-70" /><div className="relative z-10"><p className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.19em] text-cyan-100"><Orbit size={14} /> Payment DNA sphere</p><p className="mt-1 text-xs text-slate-500">An orbital representation of observed behavior, evidence, and limitations.</p></div><div className="absolute inset-x-2 top-12 bottom-24 sm:inset-x-10"><IntelligenceCore state={coreState} customers={[customer]} /></div><div className="holo-panel absolute bottom-6 left-6 z-10 hidden w-[255px] rounded-2xl p-4 lg:block"><p className="text-[9px] font-semibold uppercase tracking-[.15em] text-cyan-200">Behavior state</p><p className="mt-2 text-2xl font-semibold capitalize text-white">{profile.state.replaceAll("_", " ")}</p><p className="mt-2 text-xs leading-5 text-slate-400">{profile.explanation}</p></div><div className="holo-panel absolute bottom-6 right-6 z-10 hidden w-[240px] rounded-2xl p-4 lg:block"><p className="text-[9px] font-semibold uppercase tracking-[.15em] text-violet-200">Observed orbit</p><div className="mt-3 grid grid-cols-2 gap-3"><OrbitMetric label="Frequency" value={profile.paymentFrequencyPer30Days === null ? "—" : `${profile.paymentFrequencyPer30Days.toFixed(1)}/30d`} /><OrbitMetric label="Cadence" value={profile.averageDaysBetweenPayments === null ? "—" : `${profile.averageDaysBetweenPayments.toFixed(1)}d`} /><OrbitMetric label="Recency" value={profile.daysSinceLastPayment === null ? "—" : `${profile.daysSinceLastPayment}d`} /><OrbitMetric label="History" value={profile.observedHistoryDays === null ? "—" : `${profile.observedHistoryDays}d`} /></div></div><div className="absolute inset-x-4 bottom-4 z-10 rounded-2xl border border-white/[.09] bg-[#071126]/75 p-3 backdrop-blur-xl sm:inset-x-6"><IntelligenceLifecycle state={coreState} compact /></div></section>

    <section className="grid gap-4 lg:grid-cols-[.92fr_1.08fr]"><article className="holo-panel rounded-2xl p-5"><p className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.17em] text-cyan-200"><Database size={14} /> Observed payment values</p><div className="mt-4 space-y-2">{profile.currencyMetrics.length ? profile.currencyMetrics.map((metric) => <div key={metric.currency} className="rounded-xl border border-white/[.07] bg-black/10 p-3"><div className="flex items-center justify-between"><p className="font-medium text-white">{metric.currency}</p><p className="text-sm text-cyan-100">{formatCurrency(metric.totalPaymentValue, metric.currency)}</p></div><p className="mt-2 text-xs leading-5 text-slate-400">{metric.transactionCount} completed payment{metric.transactionCount === 1 ? "" : "s"} · average {metric.averagePaymentValue === null ? "not available" : formatCurrency(metric.averagePaymentValue, metric.currency)}</p></div>) : <p className="rounded-xl border border-white/[.07] bg-black/10 p-4 text-sm text-slate-500">No completed payment value is available for this payer profile.</p>}</div></article><article className="holo-panel rounded-2xl p-5"><p className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.17em] text-violet-200"><CircleAlert size={14} /> Deterministic evidence</p>{profile.sufficientForBehavioralAnalysis ? <div className="mt-4 grid grid-cols-2 gap-3"><Fact label="Observed history" value={`${profile.observedHistoryDays ?? 0} days`} /><Fact label="Consistency" value={profile.consistencyScore === null ? "not available" : `${Math.round(profile.consistencyScore * 100)}%`} /><Fact label="Behavior change" value={profile.behaviorChangeScore === null ? "not available" : `${Math.round(profile.behaviorChangeScore * 100)}%`} /><Fact label="Last completed payment" value={profile.lastPaymentAt ? formatRelativeDate(profile.lastPaymentAt) : "not available"} /></div> : <div className="mt-4 rounded-xl border border-violet-300/15 bg-violet-300/[.06] p-4"><p className="font-medium text-violet-100">Insufficient transaction history for behavioral analysis.</p><p className="mt-2 text-sm leading-6 text-slate-400">No historical behavior is manufactured. The displayed orbit remains an observed-fact view.</p></div>}<p className="mt-4 text-xs leading-5 text-slate-500">{profile.limitations[0] ?? "No additional methodology limitation was provided."}</p></article></section>

    <section className="grid gap-4 xl:grid-cols-[.9fr_1.1fr]"><article className="holo-panel rounded-2xl p-5"><div className="flex items-center justify-between gap-3"><p className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.17em] text-cyan-200"><Sparkles size={14} /> Optional AI explanation</p><button type="button" onClick={() => void requestExplanation()} disabled={ai.loading} className="focus-ring rounded-lg border border-cyan-300/20 px-3 py-1.5 text-xs font-medium text-cyan-100 hover:bg-cyan-300/[.08] disabled:opacity-50">{ai.loading ? "Analyzing…" : "Request explanation"}</button></div><p className="mt-3 text-xs leading-5 text-slate-500">AI receives structured normalized evidence only. It is separate from deterministic eligibility and cannot execute an action.</p>{ai.explanation ? <div className="mt-4 space-y-2"><Fact label="Reasoning" value={ai.explanation.reasoning} /><Fact label="What it means" value={ai.explanation.summary} /><Fact label="Recommended next step" value={ai.explanation.recommendedNextStep} /><Fact label="Limitation" value={ai.explanation.limitations} /></div> : <p className="mt-4 rounded-xl border border-white/[.07] bg-black/10 p-4 text-sm text-slate-400">{ai.message ?? "No AI explanation has been requested. Deterministic evidence remains the system of record."}</p>}</article><article className="holo-panel rounded-2xl p-5"><p className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.17em] text-violet-200"><BrainCircuit size={14} /> Detected signals</p><div className="mt-4 space-y-2">{insights.length ? insights.map((insight) => <Signal key={insight.id} insight={insight} />) : <p className="rounded-xl border border-white/[.07] bg-black/10 p-4 text-sm text-slate-500">No deterministic signal is supported by the available evidence.</p>}</div></article></section>

    <LearningPanel learning={learning} profile={profile} />

    <details className="group rounded-2xl border border-white/[.1] bg-[#09142b]/62"><summary className="focus-ring flex cursor-pointer list-none items-center justify-between gap-4 px-5 py-4 text-sm font-medium text-slate-100"><span>Open observed payment records & limitations</span><span className="text-xs text-slate-500">Secondary evidence layer</span></summary><div className="grid gap-4 border-t border-white/[.08] p-4 lg:grid-cols-2"><section className="rounded-xl border border-white/[.07] bg-black/10 p-4"><p className="text-[10px] font-semibold uppercase tracking-[.15em] text-cyan-200">Observed transaction history</p><div className="mt-4 space-y-2">{customerTransactions.length ? customerTransactions.map((transaction) => <div key={transaction.id} className="flex items-center justify-between gap-4 rounded-xl border border-white/[.07] bg-black/10 p-3"><div className="min-w-0"><p className="truncate text-sm font-medium text-slate-200">{transaction.paypalTransactionId ?? transaction.id}</p><p className="mt-1 text-xs text-slate-500">{formatRelativeDate(transaction.occurredAt)} · {transaction.status}</p></div><p className="shrink-0 text-sm font-semibold text-white">{formatCurrency(transaction.amount, transaction.currency)}</p></div>) : <p className="text-sm text-slate-500">No transaction records are available for this payer.</p>}</div></section><section className="rounded-xl border border-white/[.07] bg-black/10 p-4"><p className="text-[10px] font-semibold uppercase tracking-[.15em] text-violet-200">Methodology limitations</p><div className="mt-4 space-y-2">{profile.limitations.map((limitation) => <p key={limitation} className="rounded-xl border border-white/[.07] p-3 text-sm leading-6 text-slate-400">{limitation}</p>)}</div></section></div></details>
  </div>;
}

function Signal({ insight }: { readonly insight: Insight }) { return <div className="rounded-xl border border-white/[.07] bg-black/10 p-3"><div className="flex items-start justify-between gap-3"><p className="text-sm font-medium text-white">{insight.title}</p><span className="text-xs font-semibold text-cyan-100">{Math.round(insight.confidence * 100)}%</span></div><p className="mt-2 text-xs leading-5 text-slate-400">{insight.summary}</p>{insight.evidence[0] ? <p className="mt-2 text-xs text-slate-300">Evidence · {insight.evidence[0].value}</p> : null}</div>; }
function LearningPanel({ learning, profile }: { readonly learning: LearningState | null; readonly profile: PaymentDnaProfile }) { const history = profile.outcomeHistory; return <section className="holo-panel rounded-2xl p-5"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-[10px] font-semibold uppercase tracking-[.17em] text-cyan-200">Verified outcome → learning return</p><span className="text-xs text-slate-500">{learning ? `${learning.events.length} immutable event${learning.events.length === 1 ? "" : "s"}` : "Reading stored events…"}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-4"><Fact label="Succeeded" value={String(history.succeeded)} /><Fact label="Failed" value={String(history.failed)} /><Fact label="Pending" value={String(history.pending)} /><Fact label="Unknown" value={String(history.unknown)} /></div><div className="mt-4 space-y-2">{learning?.events.length ? learning.events.slice(-3).reverse().map((event) => <div key={event.learningEventId} className="flex flex-col justify-between gap-2 rounded-xl border border-white/[.07] bg-black/10 p-3 sm:flex-row"><div><p className="text-sm text-slate-200">{event.summary}</p><p className="mt-1 text-xs text-slate-500">{formatTimestamp(event.timestamp)} · {event.learningStatus === "applied" ? "Payment DNA updated from verified facts" : "Payment DNA unchanged"}</p></div><span className="text-[10px] font-semibold uppercase tracking-[.12em] text-cyan-100">{event.correlation}</span></div>) : <p className="rounded-xl border border-white/[.07] bg-black/10 p-3 text-sm text-slate-500">No outcome learning event is stored for this customer in the selected source.</p>}</div></section>; }
function OrbitMetric({ label, value }: { readonly label: string; readonly value: string }) { return <div><p className="text-[9px] uppercase tracking-[.12em] text-slate-500">{label}</p><p className="mt-1 text-sm text-slate-100">{value}</p></div>; }
function Fact({ label, value }: { readonly label: string; readonly value: string }) { return <div className="rounded-xl border border-white/[.07] bg-black/10 p-3"><p className="text-[9px] font-semibold uppercase tracking-[.13em] text-slate-500">{label}</p><p className="mt-2 text-sm leading-5 text-slate-200">{value}</p></div>; }
