"use client";

import { ArrowUpRight, Fingerprint, Orbit, UsersRound } from "lucide-react";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";

import { IntelligenceCore } from "@/components/3d/intelligence-core";
import { DataSourceSwitch } from "@/components/ui/data-source-switch";
import { formatCurrency, formatRelativeDate } from "@/lib/format";
import type { Customer, DataSource } from "@/types/domain";

type ConstellationState = "stable" | "declining" | "growing" | "irregular" | "inactive" | "insufficient_data";

export function CustomerNetwork({ customers, source }: { readonly customers: readonly Customer[]; readonly source: DataSource }) {
  const router = useRouter();
  const [selectedId, setSelectedId] = useState(customers[0]?.id ?? "");
  const sourceSuffix = source === "demo" ? "?source=demo" : "";
  const states = useMemo(() => Object.fromEntries(customers.map((customer) => [customer.id, constellationState(customer)])), [customers]);
  const selected = customers.find((customer) => customer.id === selectedId) ?? customers[0];

  return <div className="space-y-5">
    <section className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-cyan-200">Customer constellation</p><h1 className="mt-2 font-[family-name:var(--font-display)] text-3xl font-semibold tracking-[-.055em] text-white sm:text-5xl">Relationships are <span className="text-cyan-200">payment signatures.</span></h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">{source === "paypal_sandbox" ? "Each node is a payer entity derived from normalized PayPal Sandbox information. No customer identity is invented." : "Each node is an explicitly synthetic demo relationship with an evidence-bound Payment DNA profile."}</p></div><DataSourceSwitch source={source} sandboxConnected={source === "paypal_sandbox"} /></section>

    {customers.length === 0 ? <EmptyConstellation source={source} /> : <>
      <section className="relative isolate min-h-[630px] overflow-hidden rounded-[2rem] border border-cyan-300/15 bg-[radial-gradient(circle_at_50%_46%,rgba(12,135,213,.13),transparent_43%),rgba(5,10,25,.72)] p-4 sm:p-6">
        <div className="grid-noise pointer-events-none absolute inset-0 opacity-65" />
        <div className="relative z-10 flex items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.19em] text-cyan-100"><Orbit size={14} /> Customer nodes orbit the intelligence core</p><p className="mt-1 text-xs text-slate-500">Node size represents observed payment activity. Select a node to focus its Payment DNA.</p></div><span className="rounded-full border border-cyan-300/15 bg-cyan-300/[.06] px-2.5 py-1 text-[9px] font-semibold uppercase tracking-[.13em] text-cyan-100">{customers.length} connected</span></div>
        <div className="absolute inset-x-1 top-14 bottom-4 sm:inset-x-8"><IntelligenceCore state="analyzing" customers={customers} customerStates={states} onCustomerSelect={setSelectedId} /></div>
        {selected ? <aside className="holo-panel absolute bottom-6 left-6 z-20 hidden w-[240px] rounded-2xl p-4 lg:block"><p className="flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[.15em] text-cyan-200"><Fingerprint size={13} /> Focused relationship</p><p className="mt-3 text-lg font-semibold text-white">{selected.displayName}</p><p className="mt-1 text-xs capitalize text-slate-400">{states[selected.id]} payment state</p><div className="mt-4 flex items-end justify-between"><div><p className="text-[9px] uppercase tracking-[.13em] text-slate-500">Activity</p><p className="mt-1 text-xl font-semibold text-cyan-100">{selected.totalPayments}</p></div><button type="button" onClick={() => router.push(`/customers/${selected.id}${sourceSuffix}`)} className="focus-ring inline-flex items-center gap-1 rounded-lg border border-cyan-300/20 px-2.5 py-2 text-xs text-cyan-100 hover:bg-cyan-300/[.08]">Inspect <ArrowUpRight size={13} /></button></div></aside> : null}
        <div className="absolute right-6 top-24 z-20 hidden space-y-2 text-[10px] lg:block"><Legend color="bg-cyan-200" label="stable" /><Legend color="bg-emerald-300" label="growing" /><Legend color="bg-amber-300" label="declining / inactive" /><Legend color="bg-rose-300" label="irregular" /></div>
      </section>

      <section className="overflow-x-auto pb-1"><div className="flex min-w-max gap-3">{customers.map((customer) => <button key={customer.id} type="button" onClick={() => setSelectedId(customer.id)} className={`focus-ring group w-[190px] shrink-0 rounded-2xl border p-3 text-left transition ${selected?.id === customer.id ? "border-cyan-300/35 bg-cyan-300/[.09]" : "border-white/[.08] bg-white/[.025] hover:-translate-y-1 hover:border-cyan-300/20"}`}><span className={`mb-3 grid size-9 place-items-center rounded-full border text-xs font-semibold ${nodeTone(states[customer.id] ?? "stable")}`}>{customer.initials}</span><span className="block truncate text-sm font-medium text-white">{customer.displayName}</span><span className="mt-1 block text-xs capitalize text-slate-500">{states[customer.id]} · {customer.totalPayments} payment{customer.totalPayments === 1 ? "" : "s"}</span><span className="mt-3 flex items-center justify-between text-xs text-cyan-100"><span>{formatCustomerValue(customer)}</span><ArrowUpRight size={14} className="opacity-0 transition group-hover:opacity-100" /></span></button>)}</div></section>

      {selected ? <section className="grid gap-4 lg:grid-cols-[.88fr_1.12fr]"><article className="holo-panel rounded-2xl p-5"><p className="text-[10px] font-semibold uppercase tracking-[.17em] text-cyan-200">Selected Payment DNA</p><h2 className="mt-3 text-2xl font-semibold tracking-[-.04em] text-white">{selected.displayName}</h2><p className="mt-2 text-sm capitalize text-slate-400">{states[selected.id]} relationship · last observed {selected.lastPaymentAt ? formatRelativeDate(selected.lastPaymentAt) : "not provided"}</p><div className="mt-5 grid grid-cols-2 gap-3"><Fact label="Observed payments" value={String(selected.totalPayments)} /><Fact label="Observed value" value={formatCustomerValue(selected)} /><Fact label="Relationship" value={selected.segment.replaceAll("_", " ")} /><Fact label="Source" value={source === "demo" ? "Demo" : "Sandbox"} /></div></article><article className="holo-panel rounded-2xl p-5"><p className="text-[10px] font-semibold uppercase tracking-[.17em] text-violet-200">Constellation interpretation</p><p className="mt-3 text-lg font-medium text-white">{descriptionFor(selected, states[selected.id] ?? "stable")}</p><p className="mt-3 text-sm leading-6 text-slate-400">Payment DNA is an evidence-bound view of this relationship. Clicking inspect opens the orbital detail view; it does not trigger a customer action.</p><button type="button" onClick={() => router.push(`/customers/${selected.id}${sourceSuffix}`)} className="focus-ring mt-5 inline-flex items-center gap-2 rounded-xl bg-cyan-200 px-4 py-2.5 text-sm font-semibold text-slate-950 hover:bg-cyan-100">Inspect customer intelligence <ArrowUpRight size={15} /></button></article></section> : null}
    </>}
  </div>;
}

function constellationState(customer: Customer): ConstellationState { const state = customer.paymentDna?.state; if (state === "declining") return "declining"; if (state === "unusual" || customer.risk === "high" || customer.risk === "critical") return "irregular"; if (state === "watch" || state === "delayed" || customer.segment === "at_risk") return "inactive"; if (customer.paymentDna?.recentChangePercent && customer.paymentDna.recentChangePercent > 0) return "growing"; return customer.paymentDna ? "stable" : "insufficient_data"; }
function nodeTone(state: ConstellationState): string { return { stable: "border-cyan-300/25 bg-cyan-300/[.08] text-cyan-100", growing: "border-emerald-300/25 bg-emerald-300/[.08] text-emerald-100", declining: "border-amber-300/25 bg-amber-300/[.08] text-amber-100", irregular: "border-rose-300/25 bg-rose-300/[.08] text-rose-100", inactive: "border-amber-300/25 bg-amber-300/[.08] text-amber-100", insufficient_data: "border-slate-300/20 bg-slate-300/[.06] text-slate-300" }[state]; }
function formatCustomerValue(customer: Customer): string { if (customer.primaryCurrency && customer.totalValue !== null) return formatCurrency(customer.totalValue, customer.primaryCurrency); const values = Object.entries(customer.valueByCurrency).sort(([left], [right]) => left.localeCompare(right)); return values.length ? values.map(([currency, value]) => formatCurrency(value, currency)).join(" · ") : "—"; }
function Legend({ color, label }: { readonly color: string; readonly label: string }) { return <p className="flex items-center gap-2 text-slate-400"><span className={`size-1.5 rounded-full ${color}`} />{label}</p>; }
function Fact({ label, value }: { readonly label: string; readonly value: string }) { return <div className="rounded-xl border border-white/[.07] bg-black/10 p-3"><p className="text-[9px] font-semibold uppercase tracking-[.13em] text-slate-500">{label}</p><p className="mt-2 text-sm capitalize text-slate-200">{value}</p></div>; }
function descriptionFor(customer: Customer, state: ConstellationState): string { if (state === "growing") return `${customer.displayName} is shown as growing only from the available normalized payment relationship.`; if (state === "declining" || state === "inactive") return `${customer.displayName} needs review; PayPulse does not imply a cause beyond the observed payment pattern.`; if (state === "irregular") return `${customer.displayName} has an irregularity signal requiring human review, not an automatic intervention.`; if (state === "insufficient_data") return `${customer.displayName} has too little payer-attributed history for behavioral analysis.`; return `${customer.displayName} is currently stable within the available source evidence.`; }
function EmptyConstellation({ source }: { readonly source: DataSource }) { return <section className="holo-panel grid min-h-[420px] place-items-center rounded-[2rem] p-8 text-center"><div><UsersRound className="mx-auto text-cyan-200" size={30} /><h2 className="mt-4 text-xl font-semibold text-white">No customer nodes are available yet.</h2><p className="mt-2 max-w-md text-sm leading-6 text-slate-400">{source === "paypal_sandbox" ? "PayPal Sandbox reporting did not return payer-attributed records for this bounded source view. PayPulse does not invent customer entities." : "No explicit demo customer records are available."}</p></div></section>; }
