import Link from "next/link";
import { DatabaseZap, ShieldAlert } from "lucide-react";

import { CoreFallback } from "@/components/3d/core-fallback";
import type { DataSourceErrorCategory } from "@/server/data/provider";
import type { PayPalSandboxCapabilityStatus } from "@/server/paypal/capabilities";

export function DataSourceUnavailable({ message, category, path, capabilities }: { readonly message: string; readonly category: DataSourceErrorCategory; readonly path: string; readonly capabilities?: PayPalSandboxCapabilityStatus }) {
  const reportingUnsupported = capabilities?.transactionSearch === "unsupported" || category === "unsupported_capability";
  const currentCapabilities = capabilities ?? { source: "paypal_sandbox" as const, oauth: reportingUnsupported ? "available" as const : "unavailable" as const, transactionSearch: reportingUnsupported ? "unsupported" as const : "unavailable" as const };

  return <div className="space-y-5"><section className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-violet-200">PayPal Sandbox capability HUD</p><h1 className="mt-2 font-[family-name:var(--font-display)] text-3xl font-semibold tracking-[-.05em] text-white sm:text-4xl">The intelligence field is <span className="text-amber-100">source-aware.</span></h1></div><span className="w-fit rounded-full border border-amber-300/20 bg-amber-300/[.08] px-2.5 py-1 text-[9px] font-semibold uppercase tracking-[.13em] text-amber-100">{category.replaceAll("_", " ")}</span></section><section className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(330px,.8fr)]"><div className="holo-panel min-h-[360px] rounded-[2rem] p-3"><CoreFallback state="idle" /></div><article className="holo-panel rounded-2xl p-5"><p className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.17em] text-amber-100"><ShieldAlert size={14} /> {reportingUnsupported ? "PayPal reporting" : "Sandbox source"}</p><h2 className="mt-3 text-xl font-semibold text-white">{reportingUnsupported ? "Transaction reporting unavailable" : "Sandbox data is unavailable"}</h2><p className="mt-3 text-sm leading-6 text-slate-400">{message}</p><dl className="mt-5 grid gap-2"><CapabilityLine label="PayPal Sandbox OAuth" value={currentCapabilities.oauth} /><CapabilityLine label="Transaction reporting" value={currentCapabilities.transactionSearch} /><CapabilityLine label="Available path" value="PayPulse-created Sandbox verification" /></dl><p className="mt-4 text-xs leading-5 text-slate-500">No demo payment record is substituted for PayPal data. The dedicated, merchant-approved Sandbox verification flow remains a separate server-side capability.</p><Link href={`${path}?source=demo`} className="focus-ring mt-5 inline-flex items-center gap-2 rounded-xl border border-cyan-300/25 px-3.5 py-2.5 text-sm font-semibold text-cyan-100 hover:bg-cyan-300/[.08]"><DatabaseZap size={15} /> Explore clearly labeled Demo Mode</Link></article></section></div>;
}
function CapabilityLine({ label, value }: { readonly label: string; readonly value: string }) { const tone = value === "available" ? "text-emerald-200" : value === "unsupported" ? "text-amber-100" : value.includes("verification") ? "text-cyan-100" : "text-slate-300"; return <div className="flex items-center justify-between gap-3 rounded-lg border border-white/[.07] bg-black/10 px-3 py-2.5"><dt className="text-xs text-slate-500">{label}</dt><dd className={`text-xs font-medium ${tone}`}>{value.replaceAll("_", " ")}</dd></div>; }
